export const CREATE_SERVICIO = "CREATE_SERVICIO";

export const RETRIEVE_SERVICIOS = "RETRIEVE_SERVICIOS";

export const UPDATE_SERVICIO = "UPDATE_SERVICIO";

export const DELETE_SERVICIO = "DELETE_SERVICIO";